### ISSUE TITLE
Virtual Environment

### ISSUE THREAD

**Issue by chuoguejiofor** [yuxiao-pan/IST303-Group-Project#7]
Maybe we should consider leaving the venv out of the version control and using a requirements.txt as noted here:
[1](https://medium.com/@jtpaasch/the-right-way-to-use-virtual-environments-1bc255a0cba7)
[2](http://libzx.so/main/learning/2016/03/13/best-practice-for-virtualenv-and-git-repos.html)

**Comment by nash90** [comment]
Hi chu, thanks for the suggestion. 
I think the idea to just use requirements.txt with library versions info was good, as long as we have a one command installer of library when repository is fresh cloned.
Unfortunately the solution does not address that. I think this way all members will have to install all the library one by one manually during first time clone use.
